name: Terraform Apply

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  preview:
    name: Apply Terraform changes on merge
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
