name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    name: Plan Changes
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Dependencies
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Configure Devbox Shell Environment
        run: |
          eval "$(devbox shellenv)"
          printenv >> $GITHUB_ENV

      - name: List changed stacks
        id: list-changed
        run: echo "out=$(terramate list --changed)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        if: steps.list-changed.outputs.out
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"

      - name: Run Terraform Init
        if: steps.list-changed.outputs.out
        run: |
          terramate run --changed -- terraform init

      - name: Run Terraform Plan
        if: steps.list-changed.outputs.out
        run: |
          terramate run \
            --changed \
            --continue-on-error \
            --parallel 3 \
            -- \
            terraform plan -input=false -out=plan.tfplan
